### ISSUE TITLE
Deno 模板部署失败

### ISSUE THREAD

**Issue by hu-qi** [TencentCloudBase/cloudbase-templates#53]
```
tcb new deno_hello deno
cd deno_hello
tcb
```

gpdi@Mac-mini deno % tcb  new deno_hello deno
CloudBase CLI 1.5.0
CloudBase Framework 1.6.18
FetchError: network timeout at: https://iaas.cloud.tencent.com/tcb_refresh
    at Timeout.<anonymous> (/usr/local/lib/node_modules/@cloudbase/cli/node_modules/node-fetch/lib/index.js:1454:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
✖ network timeout at: https://iaas.cloud.tencent.com/tcb_refresh
gpdi@Mac-mini deno % tcb  new deno_hello deno
CloudBase CLI 1.5.0
CloudBase Framework 1.6.18
✔ 请选择环境所在地域 · 上海
✔ 请选择关联环境 · deno-demo - [deno-demo-3ghgaf7pa8d97b90:按量计费]
✔ 创建应用 deno_hello 成功！

ℹ 👉 执行命令 cd deno_hello 进入文件夹
ℹ 👉 开发完成后，执行命令 tcb 一键部署
gpdi@Mac-mini deno % cd deno_hello
gpdi@Mac-mini deno_hello % code .
gpdi@Mac-mini deno_hello % tcb
CloudBase CLI 1.5.0
CloudBase Framework 1.6.18
✔ 是否使用云开发部署当前项目 </Volumes/PhiHardisk H1/learn/deno/deno_hello> ？ (Y/n) · true
   ______ __                   __ ____
  / ____// /____   __  __ ____/ // __ ) ____ _ _____ ___
 / /    / // __ \ / / / // __  // __  |/ __ `// ___// _ \
/ /___ / // /_/ // /_/ // /_/ // /_/ // /_/ /(__  )/  __/
\_________\____/ \__,_/ \__,_//_____/ \__,_//____/ \___/       __
   / ____/_____ ____ _ ____ ___   ___  _      __ ____   _____ / /__
  / /_   / ___// __ `// __ `__ \ / _ \| | /| / // __ \ / ___// //_/
 / __/  / /   / /_/ // / / / / //  __/| |/ |/ // /_/ // /   / ,<
/_/    /_/    \__,_//_/ /_/ /_/ \___/ |__/|__/ \____//_/   /_/|_|

 CloudBase Framework  info     Version v1.6.18
 CloudBase Framework  info     Github: https://github.com/Tencent/cloudbase-framework

 CloudBase Framework  info     EnvId deno-demo-3ghgaf7pa8d97b90
 CloudBase Framework  info     Validate config file success.
 CloudBase Framework  info     AppName deno-app
 CloudBase Framework  info     📦 install plugins
 CloudBase Framework  info     callHooks 'preDeploy'
+ @cloudbase/framework-plugin-deno@1.6.18
updated 4 packages in 3.261s

26 packages are looking for funding
  run `npm fund` for details

 CloudBase Framework  info     🔧 init: deno...
 CloudBase Framework  info     🔨 build: deno...
 CloudBase Framework  info     🧬 compile: deno...
 CloudBase Framework  info     callHooks 'postCompile'
正在部署[░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 100% 155.0 s
 CloudBase Framework  error    [DEPLOY_ERROR]
部署失败，错误信息：1699395_DescribeCloudBaseRunServer_[800003][800003]read --allow-run --allow-write --allow-net -f -q --unstable https://deno.land/x/denon/denon.ts
 ---> Running in 5b75c1cbc737
Warning Implicitly using latest version (2.4.7) for https://deno.land/x/denon/denon.ts
error: TS2339 [ERROR]: Property 'host' does not exist on type 'NetPermissionDescriptor'.
              return pd.host
                        ~~~~
    at https://deno.land/std@0.85.0/permissions/mod.ts:17:25

TS2339 [ERROR]: Property 'host' does not exist on type 'NetPermissionDescriptor'.
                ? `--allow-${pd.name}=${pd.host}`
                                           ~~~~
    at https://deno.land/std@0.85.0/permissions/mod.ts:18:44

Found 2 errors.
The command '/bin/sh -c deno install --allow-read --allow-run --allow-write --allow-net -f -q --unstable https://deno.land/x/denon/denon.ts' returned a non-zero code: 1
尝试 重新构建;查看 构建详情;检查Dockerfile 是否位于正确位置: ./Dockerfile;提交工单，并在 问题描述 中附上以下信息：环境id：deno-demo-3ghgaf7pa8d97b90；服务名称：deno-app；版本：deno-app-001；状态：构建失败;， 请求RequestId：6beef91e-5383-4a07-b0a5-7e89e2f62d90
 CloudBase Framework  info     部署日志: '/Users/gpdi/cloudbase-framework/logs/2021-02-09_16-42-16.log'

log；

```
Tue Feb 09 2021 16:42:40 GMT+0800 (China Standard Time) 23.8 CloudBase Framework::info Version [32mv1.6.18[39m
Tue Feb 09 2021 16:42:40 GMT+0800 (China Standard Time) 23.8 CloudBase Framework::info Github: [1m[36m]8;;https://github.com/Tencent/cloudbase-frameworkhttps://github.com/Tencent/cloudbase-framework]8;;[39m[22m

Tue Feb 09 2021 16:42:40 GMT+0800 (China Standard Time) 23.8 CloudBase Framework::info EnvId [32mdeno-demo-3ghgaf7pa8d97b90[39m
Tue Feb 09 2021 16:42:40 GMT+0800 (China Standard Time) 23.9 CloudBase Framework::debug 本地构建，本地存在配置文件 {
  functionRoot: './functions',
  functions: [],
  version: '2.0',
  envId: 'deno-demo-3ghgaf7pa8d97b90',
  '$schema': 'https://framework-1258016615.tcloudbaseapp.com/schema/latest.json',
  framework: {
    name: 'deno-app',
    plugins: {
      deno: {
        use: '@cloudbase/framework-plugin-deno',
        inputs: { dockerImage: 'debian:latest', runtime: '1.6.3' }
      }
    }
  },
  region: 'ap-shanghai'
} 
Tue Feb 09 2021 16:42:40 GMT+0800 (China Standard Time) 24.1 CloudBase Framework::debug 远程不存在同名项目，新建项目
Tue Feb 09 2021 16:42:40 GMT+0800 (China Standard Time) 24.1 CloudBase Framework::debug 项目配置信息 'rcConfig' {
  functionRoot: './functions',
  functions: [],
  version: '2.0',
  envId: 'deno-demo-3ghgaf7pa8d97b90',
  '$schema': 'https://framework-1258016615.tcloudbaseapp.com/schema/latest.json',
  framework: {
    name: 'deno-app',
    plugins: {
      deno: {
        use: '@cloudbase/framework-plugin-deno',
        inputs: { dockerImage: 'debian:latest', runtime: '1.6.3' }
      }
    }
  },
  region: 'ap-shanghai'
} 'extraData' {} 'projectName' 'deno-app' 
Tue Feb 09 2021 16:42:40 GMT+0800 (China Standard Time) 24.1 CloudBase Framework::debug RC 配置文件变更 false {
  functionRoot: './functions',
  functions: [],
  version: '2.0',
  envId: 'deno-demo-3ghgaf7pa8d97b90',
  '$schema': 'https://framework-1258016615.tcloudbaseapp.com/schema/latest.json',
  framework: {
    name: 'deno-app',
    plugins: {
      deno: {
        use: '@cloudbase/framework-plugin-deno',
        inputs: { dockerImage: 'debian:latest', runtime: '1.6.3' }
      }
    }
  },
  region: 'ap-shanghai'
} 
Tue Feb 09 2021 16:42:40 GMT+0800 (China Standard Time) 24.1 CloudBase Framework::debug Framework 配置文件变更 false {
  name: 'deno-app',
  plugins: {
    deno: {
      use: '@cloudbase/framework-plugin-deno',
      inputs: { dockerImage: 'debian:latest', runtime: '1.6.3' }
    }
  }
} 
Tue Feb 09 2021 16:42:40 GMT+0800 (China Standard Time) 24.1 CloudBase Framework::info Validate config file success.
Tue Feb 09 2021 16:42:40 GMT+0800 (China Standard Time) 24.1 CloudBase Framework::info AppName [32mdeno-app[39m
Tue Feb 09 2021 16:42:40 GMT+0800 (China Standard Time) 24.1 CloudBase Framework::debug appConfig {
  name: 'deno-app',
  plugins: {
    deno: {
      use: '@cloudbase/framework-plugin-deno',
      inputs: { dockerImage: 'debian:latest', runtime: '1.6.3' }
    }
  }
} 
Tue Feb 09 2021 16:42:41 GMT+0800 (China Standard Time) 24.4 CloudBase Framework::info 📦 install plugins
Tue Feb 09 2021 16:42:41 GMT+0800 (China Standard Time) 24.4 CloudBase Framework::debug initHooks {} 
Tue Feb 09 2021 16:42:41 GMT+0800 (China Standard Time) 24.4 CloudBase Framework::debug resolve plugin @cloudbase/framework-plugin-deno@1.6.18: use 0.00 s, mismatch：true, resolved version：1.6.18
Tue Feb 09 2021 16:42:41 GMT+0800 (China Standard Time) 24.4 CloudBase Framework::debug deploy '' '' 
Tue Feb 09 2021 16:42:41 GMT+0800 (China Standard Time) 24.4 CloudBase Framework::info callHooks 'preDeploy' 
Tue Feb 09 2021 16:42:46 GMT+0800 (China Standard Time) 29.7 CloudBase Framework::info 🔧 init: deno...
Tue Feb 09 2021 16:42:46 GMT+0800 (China Standard Time) 29.7 CloudBase Framework::debug DenoPlugin: init {
  dockerImage: 'debian:latest',
  runtime: '1.6.3',
  denonVersion: '',
  entry: '',
  autoBuild: true,
  serviceName: 'deno-app',
  servicePath: '/deno-app',
  projectPath: '.'
} 
Tue Feb 09 2021 16:42:46 GMT+0800 (China Standard Time) 29.7 CloudBase Framework::info 🔨 build: deno...
Tue Feb 09 2021 16:42:46 GMT+0800 (China Standard Time) 29.7 CloudBase Framework::debug DenoPlugin: build {
  dockerImage: 'debian:latest',
  runtime: '1.6.3',
  denonVersion: '',
  entry: '',
  autoBuild: true,
  serviceName: 'deno-app',
  servicePath: '/deno-app',
  projectPath: '.'
} 
Tue Feb 09 2021 16:42:56 GMT+0800 (China Standard Time) 40.1 CloudBase Framework::debug ContainerPlugin: init {
  dockerImage: 'debian:latest',
  runtime: '1.6.3',
  denonVersion: '',
  entry: '',
  autoBuild: true,
  serviceName: 'deno-app',
  servicePath: '/deno-app',
  projectPath: '.',
  localAbsolutePath: '/Users/gpdi/cloudbase-framework/builds/cloudbase-deno-build-1612860166334/deno-app'
} 
Tue Feb 09 2021 16:42:57 GMT+0800 (China Standard Time) 40.5 CloudBase Framework::debug Container Plugin Inputs 'cloud' {} 'mode' {} 
Tue Feb 09 2021 16:42:57 GMT+0800 (China Standard Time) 40.5 CloudBase Framework::debug ContainerPlugin: build {
  uploadType: 'package',
  description: '基于云开发 CloudBase Framework 部署的云托管',
  isPublic: true,
  flowRatio: 100,
  cpu: 0.25,
  mem: 0.5,
  minNum: 0,
  maxNum: 10,
  policyType: 'cpu',
  policyThreshold: 60,
  containerPort: 80,
  dockerfilePath: './Dockerfile',
  buildDir: './',
  version: '1.0.0',
  localPath: './',
  envVariables: {},
  dockerImage: 'debian:latest',
  runtime: '1.6.3',
  denonVersion: '',
  entry: '',
  autoBuild: true,
  serviceName: 'deno-app',
  servicePath: '/deno-app',
  projectPath: '.',
  localAbsolutePath: '/Users/gpdi/cloudbase-framework/builds/cloudbase-deno-build-1612860166334/deno-app'
} 
Tue Feb 09 2021 16:42:57 GMT+0800 (China Standard Time) 40.9 CloudBase Framework::debug describeCloudBaseBuildService {
  DownloadHeaders: [],
  DownloadUrl: '',
  PackageName: 'deno-app.zip',
  PackageVersion: '1612860177',
  RequestId: '802b362d-31fb-4ecc-b08d-f147558007d3',
  UploadHeaders: [],
  UploadUrl: 'https://cloudaccess-run-1258016615.cos.ap-shanghai.myqcloud.com/home%2F922d0822225540ed9db967c5ef2bb198%2Fdeno-demo-3ghgaf7pa8d97b90-deno-app_1612860177_FnssTwx2.zip?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKIDYqreAvj0McQ8bplDBtRUJcfwwlL299NL%26q-sign-time%3D1612860177%3B1613464977%26q-key-time%3D1612860177%3B1613464977%26q-header-list%3Dhost%26q-url-param-list%3D%26q-signature%3D8cb9117d3c8dba2d20885f3e69bc35b7c4ed054d'
} 'deno-app' '/Users/gpdi/cloudbase-framework/builds/cloudbase-container-build-1612860176735/deno-app.zip' 
Tue Feb 09 2021 16:42:58 GMT+0800 (China Standard Time) 41.8 CloudBase Framework::info 🧬 compile: deno...
Tue Feb 09 2021 16:42:58 GMT+0800 (China Standard Time) 41.8 CloudBase Framework::debug DenoPlugin: compile {
  dockerImage: 'debian:latest',
  runtime: '1.6.3',
  denonVersion: '',
  entry: '',
  autoBuild: true,
  serviceName: 'deno-app',
  servicePath: '/deno-app',
  projectPath: '.'
} 
Tue Feb 09 2021 16:42:58 GMT+0800 (China Standard Time) 41.8 CloudBase Framework::debug ContainerPlugin: compile {
  uploadType: 'package',
  description: '基于云开发 CloudBase Framework 部署的云托管',
  isPublic: true,
  flowRatio: 100,
  cpu: 0.25,
  mem: 0.5,
  minNum: 0,
  maxNum: 10,
  policyType: 'cpu',
  policyThreshold: 60,
  containerPort: 80,
  dockerfilePath: './Dockerfile',
  buildDir: './',
  version: '1.0.0',
  localPath: './',
  envVariables: {},
  dockerImage: 'debian:latest',
  runtime: '1.6.3',
  denonVersion: '',
  entry: '',
  autoBuild: true,
  serviceName: 'deno-app',
  servicePath: '/deno-app',
  projectPath: '.',
  localAbsolutePath: '/Users/gpdi/cloudbase-framework/builds/cloudbase-deno-build-1612860166334/deno-app'
} 
Tue Feb 09 2021 16:42:58 GMT+0800 (China Standard Time) 41.8 CloudBase Framework::info callHooks 'postCompile' 
Tue Feb 09 2021 16:42:58 GMT+0800 (China Standard Time) 41.8 CloudBase Framework::debug hooks.genSAM {} 
Tue Feb 09 2021 16:42:58 GMT+0800 (China Standard Time) 41.9 CloudBase Framework::debug sam:install {
  TCBSAMFormatVersion: '2020-06-15',
  License: 'MIT',
  Description: '基于 CloudBase Framework 构建',
  Category: 'CloudApp',
  Tags: [],
  SourceUrl: 'https://github.com/Tencent/cloudbase-framework',
  ReleaseNotesUrl: 'https://github.com/Tencent/cloudbase-framework/releases',
  IconUrl: 'https://main.qcloudimg.com/raw/f87b49914efe502722f9aa128f5d8865/hello_world.svg',
  IntroUrl: 'https://cloud.tencent.com/document/product/876/44547',
  ChangeLog: [ { Title: '1.0.0', Content: [ '初次发布' ] } ],
  Author: {
    AuthorName: 'Tencent CloudBase',
    Email: 'cloudbase@tencent.com',
    Url: 'https://github.com/Tencent/cloudbase-framework'
  },
  Contributors: [
    {
      AuthorName: 'Tencent CloudBase',
      Email: 'cloudbase@tencent.com',
      Url: 'https://github.com/Tencent/cloudbase-framework'
    }
  ],
  Name: 'deno-app',
  Version: '1.0.0',
  DisplayName: 'deno-app',
  Globals: { Environment: { Variables: {} } },
  Resources: {
    DenoApp: {
      Type: 'CloudBase::CloudBaseRun',
      Properties: {
        ServerName: 'deno-app',
        Description: '基于云开发 CloudBase Framework 部署的云托管',
        isPublic: true,
        UploadType: 'package',
        FlowRatio: 100,
        Cpu: 0.25,
        Mem: 0.5,
        MinNum: 0,
        MaxNum: 10,
        PolicyType: 'cpu',
        PolicyThreshold: 60,
        ContainerPort: 80,
        DockerfilePath: './Dockerfile',
        BuildDir: './',
        HttpPath: '/deno-app',
        EnvParams: '{}',
        PackageName: 'deno-app.zip',
        PackageVersion: '1612860177'
      }
    }
  },
  EntryPoint: [
    {
      Label: '服务入口',
      EntryType: 'HttpService',
      HttpEntryPath: '/deno-app'
    }
  ]
} 
Tue Feb 09 2021 16:43:05 GMT+0800 (China Standard Time) 48.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:43:10 GMT+0800 (China Standard Time) 54.0 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:43:15 GMT+0800 (China Standard Time) 58.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:43:20 GMT+0800 (China Standard Time) 63.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:43:25 GMT+0800 (China Standard Time) 68.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:43:30 GMT+0800 (China Standard Time) 74.0 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:43:35 GMT+0800 (China Standard Time) 78.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:43:40 GMT+0800 (China Standard Time) 83.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:43:45 GMT+0800 (China Standard Time) 89.0 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:43:50 GMT+0800 (China Standard Time) 94.0 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:43:55 GMT+0800 (China Standard Time) 98.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:44:00 GMT+0800 (China Standard Time) 103.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:44:05 GMT+0800 (China Standard Time) 108.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:44:10 GMT+0800 (China Standard Time) 113.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:44:15 GMT+0800 (China Standard Time) 118.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:44:20 GMT+0800 (China Standard Time) 123.9 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:44:25 GMT+0800 (China Standard Time) 128.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:44:30 GMT+0800 (China Standard Time) 133.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:44:35 GMT+0800 (China Standard Time) 138.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:44:40 GMT+0800 (China Standard Time) 144.1 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:44:45 GMT+0800 (China Standard Time) 148.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:44:50 GMT+0800 (China Standard Time) 153.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:44:55 GMT+0800 (China Standard Time) 158.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:45:00 GMT+0800 (China Standard Time) 163.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:45:05 GMT+0800 (China Standard Time) 168.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:45:13 GMT+0800 (China Standard Time) 177.0 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:45:15 GMT+0800 (China Standard Time) 178.9 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:45:20 GMT+0800 (China Standard Time) 183.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:45:25 GMT+0800 (China Standard Time) 188.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:45:30 GMT+0800 (China Standard Time) 193.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:45:35 GMT+0800 (China Standard Time) 198.9 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installing',
  Detail: '',
  Percent: 75
} 
Tue Feb 09 2021 16:45:40 GMT+0800 (China Standard Time) 203.8 CloudBase Framework::debug ext taskInfo {
  ExtensionId: 'deno-app-x1XZcsYc',
  Status: 'installError',
  Detail: '1699395_DescribeCloudBaseRunServer_[800003][800003]read --allow-run --allow-write --allow-net -f -q --unstable https://deno.land/x/denon/denon.ts\n' +
    ' ---> Running in 5b75c1cbc737\n' +
    '\x1B[91m\x1B[0m\x1B[33mWarning\x1B[0m Implicitly using latest version (2.4.7) for https://deno.land/x/denon/denon.ts\n' +
    "\x1B[0m\x1B[91m\x1B[0m\x1B[1m\x1B[31merror\x1B[0m: \x1B[0m\x1B[1mTS2339\x1B[0m [ERROR]: Property 'host' does not exist on type 'NetPermissionDescriptor'.\n" +
    '              return pd.host\n' +
    '\x1B[0m\x1B[31m                        ~~~~\x1B[0m\n' +
    '    at \x1B[0m\x1B[36mhttps://deno.land/std@0.85.0/permissions/mod.ts\x1B[0m:\x1B[0m\x1B[33m17\x1B[0m:\x1B[0m\x1B[33m25\x1B[0m\n' +
    '\n' +
    "\x1B[0m\x1B[1mTS2339\x1B[0m [ERROR]: Property 'host' does not exist on type 'NetPermissionDescriptor'.\n" +
    '                ? `--allow-${pd.name}=${pd.host}`\n' +
    '\x1B[0m\x1B[31m                                           ~~~~\x1B[0m\n' +
    '    at \x1B[0m\x1B[36mhttps://deno.land/std@0.85.0/permissions/mod.ts\x1B[0m:\x1B[0m\x1B[33m18\x1B[0m:\x1B[0m\x1B[33m44\x1B[0m\n' +
    '\n' +
    'Found 2 errors.\n' +
    "\x1B[0mThe command '/bin/sh -c deno install --allow-read --allow-run --allow-write --allow-net -f -q --unstable https://deno.land/x/denon/denon.ts' returned a non-zero code: 1\n" +
    '尝试 重新构建;查看 构建详情;检查Dockerfile 是否位于正确位置: ./Dockerfile;提交工单，并在 问题描述 中附上以下信息：环境id：deno-demo-3ghgaf7pa8d97b90；服务名称：deno-app；版本：deno-app-001；状态：构建失败;',
  Percent: 100
} 

```

**Comment by hu-qi** [comment]
去除 deno 版本限制之后部署正常：

```
gpdi@Mac-mini deno_hello % tcb
CloudBase CLI 1.5.0
CloudBase Framework 1.6.18
✔ 是否使用云开发部署当前项目 </Volumes/PhiHardisk H1/learn/deno/deno_hello> ？ (Y/n) · true
   ______ __                   __ ____
  / ____// /____   __  __ ____/ // __ ) ____ _ _____ ___
 / /    / // __ \ / / / // __  // __  |/ __ `// ___// _ \
/ /___ / // /_/ // /_/ // /_/ // /_/ // /_/ /(__  )/  __/
\_________\____/ \__,_/ \__,_//_____/ \__,_//____/ \___/       __
   / ____/_____ ____ _ ____ ___   ___  _      __ ____   _____ / /__
  / /_   / ___// __ `// __ `__ \ / _ \| | /| / // __ \ / ___// //_/
 / __/  / /   / /_/ // / / / / //  __/| |/ |/ // /_/ // /   / ,<
/_/    /_/    \__,_//_/ /_/ /_/ \___/ |__/|__/ \____//_/   /_/|_|


 CloudBase Framework  info     Version v1.6.18
 CloudBase Framework  info     Github: https://github.com/Tencent/cloudbase-framework

 CloudBase Framework  info     EnvId deno-demo-3ghgaf7pa8d97b90
 CloudBase Framework  info     Validate config file success.
 CloudBase Framework  info     AppName deno-app
 CloudBase Framework  info     📦 install plugins
 CloudBase Framework  info     callHooks 'preDeploy'
 CloudBase Framework  info     🔧 init: deno...
 CloudBase Framework  info     🔨 build: deno...
 CloudBase Framework  info     🧬 compile: deno...
 CloudBase Framework  info     callHooks 'postCompile'
正在部署[░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 100% 80.2 s
 CloudBase Framework  info     🚀 deploy: deno...
 CloudBase Framework  info     🚀 云托管应用部署成功,
 CloudBase Framework  info     🚀 Deno 应用部署成功
 CloudBase Framework  info     callHooks 'postDeploy'
 CloudBase Framework  info     🌐 应用入口信息:
🔗 服务入口: https://deno-demo-3ghgaf7pa8d97b90-1253880795.ap-shanghai.service.tcloudbase.com/deno-app
 CloudBase Framework  info     ✨ done
```
